name: Run Jasmine Tests

on:
  push:
    branches:
      - allrecipe-back-end
  pull_request:
    branches:
      - allrecipe-back-end

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Jasmine tests
      run: npm test

