name: Jasmine Tests on Feature Branch

on:
  push:
    branches:
      - allrecipe-back-end   # Run workflow only on pushes to 'feature-branch'
  pull_request:
    branches:
      - allrecipe-back-end   # Run workflow on pull requests targeting 'feature-branch'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

